services:
  amazonia-sufocada:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: amazonia-sufocada
    environment: 
      MAPBOX_USER: user
      MAPBOX_TOKEN: token
      CONSUMER_KEY: CONSUMER_KEY
      CONSUMER_SECRET: CONSUMER_SECRET
      BEARER_TOKEN: BEARER_TOKEN
      ACCESS_TOKEN: ACCESS_TOKEN
      ACCESS_TOKEN_SECRET: ACCESS_TOKEN_SECRET
    volumes:
      - ./compose/local/entrypoint.sh:/entrypoint.sh      
      - ./src:/home/amazonia-sufocada